Vagrant.configure(2) do |config|
   config.vm.box = "rasdaman/ubuntu1404"
   config.vm.box_check_update = false
   config.vm.synced_folder "data", "/vagrant", type: "rsync"
   config.vm.provider "virtualbox" do |vb|
     # allow 6GB RAM
     vb.memory = "6000"
     # vb.cpus = 2
   end
   config.vm.provision "shell", path: "http://download.rasdaman.org/installer/install.sh" do |s|
     s.args = "-j /vagrant/profile.json"
   end
   config.vm.provision "shell", inline: <<-SHELL
     # set the default locale
     echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale
     echo 'LC_ALL="en_US.UTF-8"' >> /etc/default/locale
   SHELL
end
