develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35733:35730"
  container_name: python-skeleton-develop
  environment:
    CT_REGISTER_MODE: auto
    ENVIRONMENT: dev
    DEBUG: "True"
    CT_URL: http://mymachine:9000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
    LOCAL_URL: http://mymachine:5700
    API_VERSION: v1
  command: develop
  volumes:
    - ./ps:/opt/ps/ps
  restart: always
